inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*

Naming/MethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/strava-ruby-client.rb"

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 256

Style/MultilineBlockChain:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/strava/version_spec.rb"
    - "spec/strava/oauth/client_spec.rb"
    - "spec/strava/oauth/config_spec.rb"
    - "spec/strava/models/activities/ride_spec.rb"
    - "spec/strava/models/activities/swim_spec.rb"
    - "spec/strava/models/activities/run_spec.rb"

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
