inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - vendor/**/*

Naming/MethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/strava-ruby-client.rb"
    - 'bin/strava-activities.rb'

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/Documentation:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 256

Style/MultilineBlockChain:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
